name: Update WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"   # 每天 0 点（UTC）跑一次
  workflow_dispatch:       # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LOC_CHART: "false"
          SHOW_LANGUAGE_PER_REPO: "false"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "false"
          SHOW_OS: "false"
          SHOW_COMMIT: "false"
